variables:
  PYTHON_VERSION: '3.11.5'
  SEMANTIC_RELEASE_GL_TOKEN: $SEMANTIC_RELEASE_GL_TOKEN
  SEMANTIC_RELEASE_TYPES: "build|ci|docs|feat|fix|perf|refactor|style|test"
  SEMANTIC_RELEASE_ALLOW_REVERT: 1


stages:
  - tests
  - release

evaluate-mr-title:
  image: registry.gitlab.com/blend-data/blenddata-docker-files/semantic-release:v0.1.1
  stage: tests
  script:
    - echo "$CI_MERGE_REQUEST_TITLE"
    - bash /evaluate_mr_title.sh "types=$SEMANTIC_RELEASE_TYPES" "allow_revert=$SEMANTIC_RELEASE_ALLOW_REVERT" "mr_title=$CI_MERGE_REQUEST_TITLE"
  only:
    - merge_request

# Linting
lint:
  image: registry.gitlab.com/blend-data/blenddata-docker-files/nox-poetry:v0.2.2-${PYTHON_VERSION}
  stage: tests
  script:
    - python -m nox -s lint
  only:
  - merge_requests


generate-git-tag:
  image: registry.gitlab.com/blend-data/blenddata-docker-files/semantic-release:v0.1.1
  stage: release
  script:
    - GL_TOKEN=$SEMANTIC_RELEASE_GL_TOKEN
    - semantic-release publish
  # Only execute when manually triggered on the main branch
  rules:
    - if: ($CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH) && ($CI_COMMIT_AUTHOR != "semantic-release <semantic-release>")
      when: manual
