# pyproject.toml
[tool.poetry]
name = "view-selection-python"
version = "0.1.0"
description = "View Selection Tool for dbt"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/<your-username>/hypermodern-python"
repository = "https://github.com/<your-username>/hypermodern-python"
keywords = ["view", "selection"]
authors = ["Bram Reinders bram.reinders@blenddata.nl"]

[tool.poetry.dependencies]
python = "^3.11.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"